export const giftShopNavigation = [
  {
    category: "Top Categories",
    categoryItem: [
      {
        icon: "Home",
        title: "Home",
        href: "/product/search/Dariry & Eggs",
      },
      {
        icon: "Popular",
        title: "Popular Products",
        href: "/product/search/Breakfast",
      },
      {
        icon: "Trending",
        title: "Trending Products",
        href: "/product/search/Frozen",
      },
      {
        icon: "Products",
        title: "All Products",
        href: "/product/search/vegetables",
      },
    ],
  },
  {
    category: "Top Categories",
    categoryItem: [
      {
        icon: "BirthdayCake",
        title: "Birthday",
        href: "/product/search/vegetables",
        child: [
          {
            title: "Pears, apples, quinces",
            href: "/product/search/Pears, apples, quinces",
          },
          {
            title: "Peaches, plums, apricots",
            href: "/product/search/Peaches, plums, apricots",
          },
          {
            title: "Grapes",
            href: "/product/search/Grapes",
          },
        ],
      },
      {
        icon: "Children",
        title: "Children's",
        href: "/product/search/Fruits & Vegetables",
        child: [
          {
            title: "Onion",
            href: "/product/search/Onion",
          },
          {
            title: "Potato",
            href: "/product/search/Potato",
          },
          {
            title: "Vegetable Pack",
            href: "/product/search/Vegetable Pack",
          },
        ],
      },
      {
        icon: "Chirstmas",
        title: "Christmas Gifts",
        href: "/product/search/Dariry & Eggs",
        child: [
          {
            title: "Pears, apples, quinces",
            href: "/product/search/Pears, apples, quinces",
          },
          {
            title: "Peaches, plums, apricots",
            href: "/product/search/Peaches, plums, apricots",
          },
          {
            title: "Grapes",
            href: "/product/search/Grapes",
          },
        ],
      },
      {
        icon: "Flower",
        title: "Flower",
        href: "/product/search/Dariry & Eggs",
      },
      {
        icon: "TeddyBear",
        title: "Teddy Bears",
        href: "/product/search/Breakfast",
      },
      {
        icon: "ValentineGift",
        title: "Valentine Gifts",
        href: "/product/search/Frozen",
      },
      {
        icon: "WeddingGift",
        title: "Wedding Gifts",
        href: "/product/search/Organic",
      },
      {
        icon: "NewYearGift",
        title: "New Year Gift",
        href: "/product/search/Canned Food",
      },
      {
        icon: "Toys",
        title: "Toys",
        href: "/product/search/Coffee & Snacks",
      },
      {
        icon: "Football",
        title: "Ball",
        href: "/product/search/Sauces & Jems",
      },
      {
        icon: "BabyToys",
        title: "Baby Toys",
        href: "/product/search/Sauces & Jems",
      },
      {
        icon: "Robot",
        title: "Robot",
        href: "/product/search/Sauces & Jems",
      },
    ],
  },
];
export const serviceList = [
  {
    icon: "Truck",
    title: "Delivery quality gift",
    subtitle1: "information on its origins",
    subtitle2: "centric approach",
  },
  {
    icon: "PickUpBox",
    title: "Gift for all Occession",
    subtitle1: "information on its origins",
    subtitle2: "centric approach",
  },
  {
    icon: "OnlineService",
    title: "Happy Service",
    subtitle1: "information on its origins",
    subtitle2: "centric approach",
  },
];
export const topCategories = [
  {
    title: "Birthday Gift",
    available: "27 Available Items",
    imgUrl: "/assets/images/Gift Shop/Product 1.png",
  },
  {
    title: "Couple Gift",
    available: "17 Available Items",
    imgUrl: "/assets/images/Gift Shop/Product 2.png",
  },
  {
    title: "Baby Doll",
    available: "27 Available Items",
    imgUrl: "/assets/images/Gift Shop/Product 4.png",
  },
];
export const popularProducts = [
  {
    price: 162,
    title: "Birthday Gift For Girl",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/pngwing.com (3).png",
    discount: 8,
    id: 7544411360,
  },
  {
    price: 98,
    title: "Gift For Boy",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 5.png",
    discount: 11,
    id: 6808422238,
  },
  {
    price: 85,
    title: "Baby Toy Gift",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 3.png",
    discount: 13,
    id: 8643586433,
  },
  {
    price: 218,
    title: "Baby Doll Gift",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 6.png",
    discount: 11,
    id: 5666445442,
  },
  {
    price: 142,
    title: "Jewellery Gift",
    rating: 4,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Gift box 2.png",
    discount: 12,
    id: 3938759640,
  },
  {
    price: 71,
    title: "Baby Doll Gift",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 6.png",
    discount: 8,
    id: 7101230747,
  },
];
export const topSailedProducts = [
  {
    price: 219,
    title: "Gold Wedding Ring",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 7.png",
    discount: 9,
    id: 6503013484,
  },
  {
    price: 209,
    title: "Gift For Baby",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 4.png",
    discount: 17,
    id: 1042471944,
  },
  {
    price: 248,
    title: "Special Gift For Young",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Gift Box.png",
    discount: 9,
    id: 1263502673,
  },
  {
    price: 111,
    title: "Gift For Boy",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 5.png",
    discount: 12,
    id: 5884344952,
  },
  {
    price: 65,
    title: "Baby Toy Gift",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 3.png",
    discount: 18,
    id: 8634030972,
  },
  {
    price: 71,
    title: "Baby Doll Gift",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 6.png",
    discount: 8,
    id: 7101230747,
  },
];
export const giftShopProducts = [
  {
    price: 219,
    title: "Gold Wedding Ring",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 7.png",
    discount: 9,
    id: 6503013484,
  },
  {
    price: 209,
    title: "Gift For Baby",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 4.png",
    discount: 17,
    id: 1042471944,
  },
  {
    price: 248,
    title: "Special Gift For Young",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Gift Box.png",
    discount: 9,
    id: 1263502673,
  },
  {
    price: 111,
    title: "Gift For Boy",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 5.png",
    discount: 12,
    id: 5884344952,
  },
  {
    price: 65,
    title: "Baby Toy Gift",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 3.png",
    discount: 18,
    id: 8634030972,
  },
  {
    price: 71,
    title: "Baby Doll Gift",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 6.png",
    discount: 8,
    id: 7101230747,
  },
  {
    price: 172,
    title: "Jewellery Gift",
    rating: 4,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Gift box 2.png",
    discount: 18,
    id: 3376292520,
  },
  {
    price: 162,
    title: "Birthday Gift For Girl",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/pngwing.com (3).png",
    discount: 8,
    id: 7544411360,
  },
  {
    price: 98,
    title: "Gift For Boy",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 5.png",
    discount: 11,
    id: 6808422238,
  },
  {
    price: 85,
    title: "Baby Toy Gift",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 3.png",
    discount: 13,
    id: 8643586433,
  },
  {
    price: 218,
    title: "Baby Doll Gift",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Product 6.png",
    discount: 11,
    id: 5666445442,
  },
  {
    price: 142,
    title: "Jewellery Gift",
    rating: 4,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/Gift box 2.png",
    discount: 12,
    id: 3938759640,
  },
];
