export const products = [
  {
    price: 250,
    published: true,
    id: "6ed34Edf65d",
    category: "Gadgets",
    name: "Samsung Galaxy-M1",
    brand: "/assets/images/brands/samsung.png",
    image: "/assets/images/products/samsung.png",
  },
  {
    price: 10,
    published: true,
    id: "6ed34Edf65d",
    category: "Grocery",
    name: "Tomatto",
    brand: "/assets/images/brands/brokshire.png",
    image: "/assets/images/products/tomato.png",
  },
  {
    price: 24,
    published: false,
    id: "6ed34Edf65d",
    category: "Beauty",
    name: "Boston Round Cream Pack",
    brand: "/assets/images/brands/levis.png",
    image: "/assets/images/products/beauty-cream.png",
  },
  {
    price: 35,
    published: true,
    id: "6ed34Edf65d",
    category: "Fashion",
    name: "Woman Party Dress",
    brand: "/assets/images/brands/raymond.png",
    image: "/assets/images/products/red-dress.png",
  },
  {
    price: 16,
    published: true,
    id: "6ed34Edf65d",
    category: "Fashion",
    name: "White Tops",
    brand: "/assets/images/brands/raymond.png",
    image: "/assets/images/products/white-tops.png",
  },
  {
    price: 26,
    published: false,
    id: "6ed34Edf65d",
    category: "Fashion",
    name: "Casual Shirt for Man",
    brand: "/assets/images/brands/raymond.png",
    image: "/assets/images/products/formal-shirt.png",
  },
  {
    price: 21,
    published: true,
    id: "6ed34Edf65d",
    category: "Fashion",
    name: "Blue Premium T-shirt",
    brand: "/assets/images/brands/raymond.png",
    image: "/assets/images/products/blu-tshirt.png",
  },
  {
    price: 12,
    published: false,
    id: "6ed34Edf65d",
    category: "Fashion",
    name: "Man Trowzer Pant",
    brand: "/assets/images/brands/raymond.png",
    image: "/assets/images/products/pnat.png",
  },
];
