export const grocery1ServiceList = [
  {
    icon: "Truck",
    title: "Fast Delivery",
    subtitle: "Start from $10",
  },
  {
    icon: "MoneyGuarantee",
    title: "Money Guarantee",
    subtitle: "7 Days Back",
  },
  {
    icon: "AlarmClock",
    title: "365 Days",
    subtitle: "For free return",
  },
  {
    icon: "Payment",
    title: "Payment",
    subtitle: "Secure system",
  },
  {
    icon: "OnlineSupport",
    title: "Online Support",
    subtitle: "24/7 daily",
  },
];
export const topSailedProducts = [
  {
    price: 146,
    title: "Fresh Line",
    rating: 2,
    imgUrl: "/assets/images/Groceries Shop/lime.png",
    discount: 7,
    id: 5761782611,
  },
  {
    price: 110,
    title: "Mini Papers",
    rating: 3,
    imgUrl: "/assets/images/Groceries Shop/MiniPeppers.png",
    discount: 9,
    id: 4473716044,
  },
  {
    price: 105,
    title: "Fresh Strawberry",
    rating: 5,
    imgUrl: "/assets/images/Groceries Shop/strawberry.png",
    discount: 6,
    id: 8672259219,
  },
  {
    price: 232,
    title: "Lemon",
    rating: 4,
    imgUrl: "/assets/images/Groceries Shop/Lemon.png",
    discount: 7,
    id: 4694350957,
  },
  {
    price: 164,
    title: "Fresh Orange",
    rating: 4,
    imgUrl: "/assets/images/Groceries Shop/Orange.png",
    discount: 11,
    id: 4330013762,
  },
];
export const grocery3Products = [
  {
    price: 146,
    title: "Fresh Line",
    rating: 2,
    imgUrl: "/assets/images/Groceries Shop/lime.png",
    discount: 7,
    id: 5761782611,
  },
  {
    price: 110,
    title: "Mini Papers",
    rating: 3,
    imgUrl: "/assets/images/Groceries Shop/MiniPeppers.png",
    discount: 9,
    id: 4473716044,
  },
  {
    price: 105,
    title: "Fresh Strawberry",
    rating: 5,
    imgUrl: "/assets/images/Groceries Shop/strawberry.png",
    discount: 6,
    id: 8672259219,
  },
  {
    price: 232,
    title: "Lemon",
    rating: 4,
    imgUrl: "/assets/images/Groceries Shop/Lemon.png",
    discount: 7,
    id: 4694350957,
  },
  {
    price: 164,
    title: "Fresh Orange",
    rating: 4,
    imgUrl: "/assets/images/Groceries Shop/Orange.png",
    discount: 11,
    id: 4330013762,
  },
  {
    price: 141,
    title: "Fresh Line",
    rating: 2,
    imgUrl: "/assets/images/Groceries Shop/lime.png",
    discount: 12,
    id: 3437114550,
  },
  {
    price: 145,
    title: "Red Apple",
    rating: 2,
    imgUrl: "/assets/images/Groceries Shop/Red apple.png",
    discount: 7,
    id: 145450158,
  },
  {
    price: 216,
    title: "Lemon",
    rating: 3,
    imgUrl: "/assets/images/Groceries Shop/Lemon.png",
    discount: 9,
    id: 6935257247,
  },
  {
    price: 198,
    title: "Offer Fruits",
    rating: 4,
    imgUrl: "/assets/images/Groceries Shop/Offer Card.png",
    discount: 12,
    id: 3805054724,
  },
];
export const grocery3offerProducts = [
  {
    title: "Till 10 Dec, 2021",
    discountOffer: "25% Special Off Today Only for Vegetables",
    imgUrl: "/assets/images/Groceries Shop/vagitable.png",
    buttonText: "Shop Now",
  },
  {
    title: "New Offer!",
    discountOffer: "15% Special Off Today Only for Fruits Item.",
    imgUrl: "/assets/images/Groceries Shop/Offer Card.png",
    buttonText: "Shop Now",
  },
];
